sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t asthamor/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true asthamor/docker-react npm run test